### ISSUE TITLE
How to debug DrivenByMoss bitwig extension in Ubuntu and VScode

### ISSUE THREAD

**Issue by laurentdebricon** [outterback/bitwig-controller-tutorial#2]
Ubuntu 18.04
sudo apt-get install default-jdk maven
install vscode java-pack extension : https://marketplace.visualstudio.com/it ... -java-pack
vim  ~/.bashrc , add at the end :
`export BITWIG_DEBUG_PORT=5005
`
logout and login 
launch bitwig-studio in a terminal and look for the message : 
BITWIG_DEBUG_PORT environment variable set to 5005 so enabling remote debugging
Listening for transport dt_socket at address: 5005

In VScode, in debug tab (ctrl+shift+D), edit launch.json configuration and add : 

```
{
			"type": "java",
			"name": "Debug Bitwig (Attach)",
			"projectName": "DrivenByMoss",
			"request": "attach",
			"hostName": "localhost",
			"port": 5005
}
```
git clone https://github.com/git-moss/DrivenByMoss.git
add the folder to VScode workspace.

Run the debug config "Debug Bitwig (Attach)"
put one breakpoint somewhere in the file you want to debug.
open a terminal :
cd DrivenBymoss
mvn install  -Dbitwig.extension.directory=/home/$(whoami)/Bitwig\ Studio/Extensions
(double check that your bitwig is installed in ~/Bitwig Studio/ The above command will build DrivenByMoss and copy the built .bitwigextension to the Extensions folder of Bitwig)

if you have a bitwig controller DrivenByMoss already setup in Bitwig, Bitwig will see that the file is different, and will reload it. Then vscode should stop at your breakpoint !!!

**Comment by laurentdebricon** [comment]
i leave it here, for google people like me :)

**Comment by outterback** [comment]
If you want to add it to the repo, just throw it in a pull request :)
